from setuptools import setup, find_packages

setup(
    name="beyondfid",
    version="0.1.0",
    packages=find_packages(),
    entry_points={
        "console_scripts": [
            "beyondfid=beyondfid.run:main",
        ],
    },
    install_requires=[
        'torch>=2.0.0',
        'torchvision>=0.15.0',
        'clip @ git+https://github.com/openai/CLIP.git',
        'av>=10.0.0',
        'ml_collections>=0.1.1',
        'pandas>=1.5.0',
        'timm>=0.9.0',
        'diffusers>=0.21.0',
        'accelerate>=0.21.0',
        'matplotlib>=3.7.0',
        'transformers>=4.30.0',
        'opencv-python>=4.8.0',
        'scikit-learn>=1.3.0',
        'numpy>=1.24.0',
        'pillow>=10.0.0',
        'tqdm>=4.65.0',
    ],
    author="Mischa Dombrowski",
    author_email="mischa.dombrowski@gmail.com",
    description="Python package to efficiently compute common metrics used for unconditional image generation",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/MischaD/BeyondFID",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires='>=3.8',
)